# Generated by Django 5.0.3 on 2024-03-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='historical_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Constr_Year', models.IntegerField()),
                ('Facts', models.TextField()),
                ('view_360deg', models.URLField(max_length=1000)),
                ('Im', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Gmap', models.URLField(max_length=1000)),
                ('Arch_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='history.archi')),
                ('Constr_Mat', models.ManyToManyField(blank=True, null=True, related_name='buildings', to='history.materials')),
            ],
        ),
    ]
