# Generated by Django 5.0.3 on 2024-03-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historical_data',
            old_name='Facts',
            new_name='Description',
        ),
    ]
