# Generated by Django 5.0.3 on 2024-03-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_country_historical_data_country_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_data',
            name='Fact',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
